#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import subprocess
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

OUT = Path("reports/output/autonomous-live")
SESSION_SCOPE = Path("scope_policy.session.yaml")
ARTEMIS_LIVE_CONFIG = OUT / "artemis-live.yaml"

RESET = "\033[0m"
BOLD = "\033[1m"
DIM = "\033[2m"
RED = "\033[91m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
BLUE = "\033[94m"
MAGENTA = "\033[95m"
CYAN = "\033[96m"
WHITE = "\033[97m"

REPORTS = {
    "live": "reports/output/autonomous-live/live-run.md",
    "preflight": "reports/output/mission-preflight/preflight.md",
    "tool_doctor": "reports/output/tool-doctor/tool-doctor.md",
    "unified": "reports/output/unified-mission/unified-mission.md",
    "verdicts": "reports/output/mission-verdicts/mission-verdicts.md",
    "evidence": "reports/output/evidence-cards/evidence-cards.md",
    "reportability": "reports/output/reportability/reportability.md",
    "final": "reports/output/report-v2/executive-report-v2.md",
    "summary": "reports/output/vulnscope-main/final-summary.md",
}

NOISE = [
    "Message from Kali developers",
    "This is a minimal installation of Kali Linux",
    "https://www.kali.org/docs/troubleshooting/common-minimum-setup/",
    "touch ~/.hushlogin",
]


def c(text: str, color: str) -> str:
    return f"{color}{text}{RESET}"


def line(char: str = "═", width: int = 96, color: str = CYAN) -> None:
    print(c(char * width, color))


def box(title: str, subtitle: str = "") -> None:
    print(c("╔" + "═" * 94 + "╗", CYAN + BOLD))
    print(c(f"║ {title:<92} ║", CYAN + BOLD))
    if subtitle:
        print(c(f"║ {subtitle:<92} ║", CYAN))
    print(c("╚" + "═" * 94 + "╝", CYAN + BOLD))


def stamp() -> str:
    return time.strftime("%H:%M:%S")


def say(tag: str, message: str, color: str = WHITE) -> None:
    print(f"{c('[' + stamp() + ']', DIM)} {c(tag.ljust(14), color + BOLD)} {message}")


def thinking(title: str, message: str, data: dict[str, Any] | None = None) -> None:
    print()
    print(c("┌─ NEURAL THINKING :: " + title, MAGENTA + BOLD))
    for part in message.split("\n"):
        print(c("│ ", MAGENTA) + part)
    if data:
        compact = json.dumps(data, ensure_ascii=False)[:1200]
        print(c("│ data: ", MAGENTA) + compact)
    print(c("└────────────────────────────────────────────────────────────────────────────", MAGENTA))


def normalize_target(raw: str) -> str:
    raw = raw.strip()
    if not raw:
        raise ValueError("Target cannot be empty")
    return raw if "://" in raw else "https://" + raw


def host_from_target(target: str) -> str:
    parsed = urlparse(normalize_target(target))
    host = parsed.hostname or parsed.netloc or target.replace("https://", "").replace("http://", "").split("/")[0]
    if not host:
        raise ValueError("Invalid target")
    return host.lower()


def write_scope(target: str, include_subdomains: bool) -> Path:
    host = host_from_target(target)
    allowed = [host]
    if include_subdomains and not host.replace(".", "").isdigit() and host != "localhost":
        allowed.append("*." + host)
    SESSION_SCOPE.write_text("\n".join([
        "name: autonomous-live-session",
        "allowed_hosts:",
        *["  - '" + item + "'" for item in allowed],
        "blocked_hosts: []",
        "allowed_schemes:",
        "  - https",
        "  - http",
        "max_requests_per_minute: 30",
        "active_testing_allowed: false",
        "authenticated_testing_allowed: true",
        "notes: 'Generated by autonomous_live_cli.py. Authorized safe review only.'",
        "",
    ]), encoding="utf-8")
    return SESSION_SCOPE


def write_artemis_config(target: str) -> Path:
    OUT.mkdir(parents=True, exist_ok=True)
    ARTEMIS_LIVE_CONFIG.write_text("\n".join([
        "targets:",
        f"  - {target}",
        "passive_only: true",
        "require_scope_policy: true",
        "interval_minutes: 360",
        "report_every_cycles: 1",
        "google_search_limit: 5",
        "max_public_records: 1000",
        "respect_rate_limits: true",
        "no_secret_values_in_reports: true",
        "notes: 'Generated by autonomous live CLI. Authorized safe review only.'",
        "",
    ]), encoding="utf-8")
    return ARTEMIS_LIVE_CONFIG


def clean_output(text: str) -> str:
    lines: list[str] = []
    skip = 0
    for raw in (text or "").splitlines():
        if skip:
            skip -= 1
            continue
        if any(n in raw for n in NOISE):
            skip = 4
            continue
        if raw.strip():
            lines.append(raw.rstrip())
    return "\n".join(lines)


def extract_interesting_lines(output: str) -> list[str]:
    keywords = ["found", "candidate", "endpoint", "subdomain", "url", "risk", "vulner", "review", "critical", "high", "medium", "low", "missing", "header", "api", "auth", "idor", "xss", "sqli", "cors", "hsts", "admin", "login"]
    lines: list[str] = []
    for line_txt in output.splitlines():
        low = line_txt.lower()
        if any(k in low for k in keywords):
            lines.append(line_txt.strip())
    return lines


def run_command(label: str, command: str, timeout: int = 3600) -> dict[str, Any]:
    say("RUNNING", label, BLUE)
    say("COMMAND", command, DIM)
    started = time.time()
    try:
        proc = subprocess.run(["bash", "-lc", command], text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, timeout=timeout)
        output = clean_output(proc.stdout)
        ok = proc.returncode == 0
        status = "OK" if ok else "FAILED"
        color = GREEN if ok else RED
        say(status, f"{label} finished in {round(time.time() - started, 2)}s", color)
        interesting = extract_interesting_lines(output)
        for item in interesting[:8]:
            print(c("   ├─ ", color) + item[:190])
        if output and not interesting and not ok:
            print(c("   └─ ", RED) + output[-600:].replace("\n", " | ")[:600])
        return {"label": label, "command": command, "ok": ok, "exit_code": proc.returncode, "seconds": round(time.time() - started, 2), "output_tail": output[-6000:]}
    except Exception as exc:
        say("ERROR", f"{label}: {exc}", RED)
        return {"label": label, "command": command, "ok": False, "error": str(exc), "seconds": round(time.time() - started, 2), "output_tail": ""}


def load_json(path: str | Path) -> Any:
    p = Path(path)
    if not p.exists():
        return None
    try:
        return json.loads(p.read_text(encoding="utf-8", errors="ignore"))
    except Exception:
        return None


def scan_report_text() -> str:
    chunks: list[str] = []
    root = Path("reports/output")
    if not root.exists():
        return ""
    for p in root.rglob("*"):
        if p.suffix.lower() in {".json", ".md", ".txt"} and p.stat().st_size < 2_500_000:
            try:
                chunks.append(p.read_text(encoding="utf-8", errors="ignore")[:220000])
            except Exception:
                pass
    return "\n".join(chunks)


def surface_snapshot(target: str, label: str) -> dict[str, list[str]]:
    host = host_from_target(target)
    base = ".".join(host.split(".")[-2:]) if "." in host else host
    text = scan_report_text()
    urls = sorted(set(re.findall(r"https?://[^\s\"'<>),]+", text)))
    domains = sorted(set(re.findall(r"\b[a-zA-Z0-9._-]+\." + re.escape(base) + r"\b", text)))
    paths = sorted(set(re.findall(r"(?<![A-Za-z0-9])/[A-Za-z0-9_./?=&%:-]{2,}", text)))
    params = sorted(set(re.findall(r"[?&]([A-Za-z0-9_:-]{2,})=", text)))
    snap = {"domains": domains[:30], "urls": urls[:30], "paths": paths[:35], "params": params[:25]}
    print()
    print(c(f"┌─ LIVE SURFACE SNAPSHOT :: {label}", CYAN + BOLD))
    print(c(f"│ Subdomains/hosts observed : {len(domains)}", CYAN))
    for item in domains[:10]:
        print(c("│   host  → ", CYAN) + item)
    print(c(f"│ URLs observed             : {len(urls)}", CYAN))
    for item in urls[:10]:
        print(c("│   url   → ", CYAN) + item[:150])
    print(c(f"│ Paths/routes observed     : {len(paths)}", CYAN))
    for item in paths[:12]:
        print(c("│   route → ", CYAN) + item[:150])
    print(c(f"│ Parameters observed       : {len(params)}", CYAN))
    if params:
        print(c("│   params→ ", CYAN) + ", ".join(params[:14]))
    print(c("└────────────────────────────────────────────────────────────────────────────", CYAN))
    return snap


def print_verdict_table() -> dict[str, Any]:
    data = load_json("reports/output/mission-verdicts/mission-verdicts.json") or {}
    rows = data.get("rows", []) if isinstance(data, dict) else []
    summary = data.get("summary", {}) if isinstance(data, dict) else {}
    print()
    box("MODULE VERDICTS", "Evidence-first result table from the autonomous mission")
    print(c(f"{'Module':<24} {'Verdict':<18} {'Severity':<10} Item Tested", BOLD + WHITE))
    print(c("─" * 96, DIM))
    for r in rows[:22]:
        module = str(r.get("module", "unknown"))[:23]
        verdict = str(r.get("verdict", "REVIEW"))[:17]
        severity = str(r.get("severity", "INFO"))[:9]
        item = str(r.get("item", "n/a"))[:45]
        color = GREEN
        if "HIGH" in verdict.upper() or severity.upper() in {"CRITICAL", "HIGH"}:
            color = RED if severity.upper() == "CRITICAL" else YELLOW
        elif "ERROR" in verdict.upper() or "MISSING" in verdict.upper() or "FAILED" in verdict.upper():
            color = RED
        print(f"{c(f'{module:<24}', CYAN)} {c(f'{verdict:<18}', color + BOLD)} {c(f'{severity:<10}', color)} {item}")
    if not rows:
        print(c("No verdict rows generated yet. Check module failures and final report.", YELLOW))
    return {"rows": rows, "summary": summary}


def final_summary(results: list[dict[str, Any]], target: str) -> dict[str, Any]:
    verdict = print_verdict_table()
    ok = len([r for r in results if r.get("ok")])
    failed = len(results) - ok
    severity = verdict.get("summary", {}).get("severity", {}) if isinstance(verdict.get("summary"), dict) else {}
    high_rows = []
    for row in verdict.get("rows", []):
        if str(row.get("severity", "")).upper() in {"CRITICAL", "HIGH"} or str(row.get("verdict", "")).upper() in {"REVIEW_HIGH", "VULNERABLE", "HIGH_PRIORITY"}:
            high_rows.append(row)
    payload = {"target": target, "tasks": len(results), "ok": ok, "failed": failed, "severity": severity, "high_priority_rows": high_rows[:30], "results": results, "reports": REPORTS}
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "live-run.json").write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    lines = [f"# VulnScope Live Autonomous Run — {target}", "", f"Tasks: `{len(results)}`", f"OK: `{ok}`", f"Failed/review: `{failed}`", "", "## High Priority Rows"]
    if high_rows:
        for row in high_rows[:30]:
            lines.append(f"- `{row.get('module')}` `{row.get('item')}` verdict=`{row.get('verdict')}` severity=`{row.get('severity')}` evidence=`{str(row.get('evidence',''))[:300]}`")
    else:
        lines.append("- No high-priority row generated. Review mission-verdicts.md for manual-review items.")
    lines += ["", "## Reports"]
    for name, path in REPORTS.items():
        lines.append(f"- {name}: `{path}`")
    (OUT / "live-run.md").write_text("\n".join(lines), encoding="utf-8")
    return payload


def stage(title: str, thought: str, steps: list[tuple[str, str, int]], workers: int, results: list[dict[str, Any]], target: str) -> None:
    print()
    box(title, "Parallel safe modules running under scope lock")
    thinking(title, thought)
    if len(steps) == 1:
        label, command, timeout = steps[0]
        results.append(run_command(label, command, timeout))
    else:
        with ThreadPoolExecutor(max_workers=max(1, min(workers, len(steps)))) as executor:
            futures = {executor.submit(run_command, label, command, timeout): label for label, command, timeout in steps}
            for fut in as_completed(futures):
                results.append(fut.result())
    surface_snapshot(target, title)


def build_steps(target: str, include_google_pair: bool, max_cycles: int) -> list[tuple[str, str, list[tuple[str, str, int]]]]:
    target_q = shlex.quote(target)
    host_q = shlex.quote(host_from_target(target))
    scope_q = shlex.quote(str(SESSION_SCOPE))
    artemis_q = shlex.quote(str(ARTEMIS_LIVE_CONFIG))
    return [
        ("STAGE 1: PREFLIGHT", "I will validate the target, scope, DNS, typo risk, and stale output state before doing deeper review.", [
            ("Mission Preflight", f"python3 mission_preflight_cli.py --target {target_q} --scope-policy {scope_q}", 600),
        ]),
        ("STAGE 2: SYSTEM READINESS + TOOL REPAIR", "I will fix optional helper tools, repair PATH issues, check coverage, and verify that the arsenal is ready before collecting evidence.", [
            ("Tool Doctor", "python3 tool_doctor_cli.py --install --yes", 1800),
            ("Tool PATH Repair", "python3 tool_path_repair_cli.py", 600),
            ("Coverage Matrix", "python3 coverage_matrix.py", 600),
            ("Mega Tools Status", "python3 mega_tools_cli.py --status", 900),
        ]),
        ("STAGE 3: AUTONOMOUS INTELLIGENCE COLLECTION", "I will collect passive target intelligence, archived URLs, subdomains, public references, and likely review areas from evidence.", [
            ("Neural Tool Mind", f"python3 tool_mind_cli.py --target {target_q} --mode crazy --install-needed --yes", 3600),
            ("Passive Domain Recon", f"python3 domain_recon_cli.py --target {host_q}", 1800),
            ("AEGIS Public Search", f"python3 aegis_public_search_cli.py --target {target_q}", 900),
            ("AEGIS Feedback Planner", f"python3 aegis_feedback_cli.py --target {target_q}", 900),
            ("ARTEMIS Passive Intelligence", f"python3 artemis_autonomous_cli.py --config {artemis_q} --scope-policy {scope_q} --once", 2400),
        ]),
        ("STAGE 4: SAFE REVIEW + HYPOTHESIS TESTING", "I will review discovered URLs, APIs, parameters, auth-sensitive routes, and candidate categories without destructive payloads.", [
            ("Safe Evidence Loop", f"python3 safe_loop_v2_cli.py --target {target_q} --mode comprehensive --scope-policy {scope_q} --max-cycles {max_cycles} --yes", 3600),
            ("Comprehensive Category Review", f"python3 comprehensive_suite_cli.py --target {target_q} --scope-policy {scope_q} --yes", 2400),
            ("Proxy Passive Bridge", f"python3 artemis_proxy_passive_cli.py --target {target_q} --limit 100", 900),
        ] + ([
            ("Two Account Precision", f"python3 google_pair_cli.py --target {target_q} --profile default --max-pages 25 --skip-login --skip-if-missing --yes", 3600),
        ] if include_google_pair else [])),
        ("STAGE 5: CORRELATION ENGINE", "I will merge evidence, build the asset graph, map API/object-auth surfaces, correlate advanced modes, and reduce duplicate/weak findings.", [
            ("Advanced Modes Correlation", f"python3 vulnscope_modes_cli.py --target {target_q} --scope-policy {scope_q}", 2400),
            ("Normalize Evidence", f"python3 normalize_cli.py --target {target_q}", 900),
            ("Asset Graph", f"python3 asset_graph_cli.py --target {target_q}", 900),
            ("API Intelligence", f"python3 api_intel_cli.py --target {target_q}", 900),
            ("Auth Differential v2", "python3 auth_diff_v2_cli.py", 900),
            ("Target History", f"python3 target_history_cli.py --target {target_q}", 900),
        ]),
        ("STAGE 6: VERDICTS + REPORTING", "I will convert evidence into readable verdict tables and final reports so the user can see what was tested, where it was found, and what needs manual validation.", [
            ("Evidence Cards", f"python3 evidence_cards_cli.py --target {target_q}", 900),
            ("Reportability Ranking", f"python3 reportability_cli.py --target {target_q}", 900),
            ("Mission Verdict Report", f"python3 mission_verdicts_cli.py --target {target_q}", 900),
            ("OMEGA Taxonomy Report", f"python3 omega_taxonomy_cli.py --target {target_q}", 900),
            ("Final Report", f"python3 report_v2_cli.py --target {target_q}", 900),
            ("JARVIS Summary", f"python3 jarvis_summary_cli.py --target {target_q}", 900),
        ]),
    ]


def plan_only(target: str, include_subdomains: bool, include_google_pair: bool, max_cycles: int) -> int:
    target = normalize_target(target)
    write_scope(target, include_subdomains)
    write_artemis_config(target)
    stages = build_steps(target, include_google_pair, max_cycles)
    print(json.dumps({"target": target, "stages": [{"name": s[0], "commands": [x[1] for x in s[2]]} for s in stages]}, indent=2))
    return 0


def run_live(target: str, include_subdomains: bool, include_google_pair: bool, workers: int, max_cycles: int) -> int:
    target = normalize_target(target)
    OUT.mkdir(parents=True, exist_ok=True)
    scope = write_scope(target, include_subdomains)
    write_artemis_config(target)
    os.environ["PYTHONUNBUFFERED"] = "1"
    print(c("\n" + "█" * 96, CYAN + BOLD))
    print(c("█" + " " * 94 + "█", CYAN + BOLD))
    print(c("█   VULNSCOPE AUTONOMOUS SECURITY INTELLIGENCE ENGINE".ljust(95) + "█", CYAN + BOLD))
    print(c("█   Neural Thinking • Live Surface Map • Parallel Modules • Final Verdicts".ljust(95) + "█", MAGENTA + BOLD))
    print(c("█" + " " * 94 + "█", CYAN + BOLD))
    print(c("█" * 96 + "\n", CYAN + BOLD))
    mission_id = "VS-" + time.strftime("%Y%m%d-%H%M%S")
    print(c(f"MISSION ID       : {mission_id}", WHITE + BOLD))
    print(c(f"TARGET           : {target}", WHITE + BOLD))
    print(c(f"SCOPE POLICY     : {scope}", WHITE))
    print(c("MODE             : Autonomous Safe Review", WHITE))
    print(c(f"PARALLEL WORKERS : {workers}", WHITE))
    print(c(f"MAX CYCLES       : {max_cycles}", WHITE))
    print(c("STATUS           : INITIALIZING", YELLOW + BOLD))
    thinking("Consent Verified", "The user confirmed authorization before this engine was launched. I will keep all modules scope-locked, evidence-first, and report-focused.", {"target": target, "include_subdomains": include_subdomains, "two_account": include_google_pair})
    results: list[dict[str, Any]] = []
    start = time.time()
    for title, thought, steps in build_steps(target, include_google_pair, max_cycles):
        stage(title, thought, steps, workers, results, target)
    payload = final_summary(results, target)
    print()
    box("FINAL OUTPUT", "Autonomous scan completed; reports saved")
    print(c(f"TARGET                  : {target}", WHITE + BOLD))
    print(c(f"TOTAL MODULE TASKS      : {payload['tasks']}", WHITE))
    print(c(f"SUCCESSFUL TASKS        : {payload['ok']}", GREEN + BOLD))
    print(c(f"FAILED / REVIEW TASKS   : {payload['failed']}", YELLOW if payload["failed"] else GREEN))
    print(c(f"TOTAL TIME              : {round(time.time() - start, 2)}s", WHITE))
    print(c("SEVERITY SUMMARY        : " + json.dumps(payload.get("severity", {}), ensure_ascii=False), WHITE))
    if payload["high_priority_rows"]:
        print(c("\nTOP HIGH-PRIORITY ROWS", RED + BOLD))
        for row in payload["high_priority_rows"][:10]:
            print(c("  ├─ ", RED) + f"[{row.get('severity')}] {row.get('module')} :: {row.get('item')} :: {row.get('verdict')}")
    else:
        print(c("\nNo high-priority row generated. Review manual candidates in mission-verdicts.md.", YELLOW))
    print(c("\nREPORTS SAVED", CYAN + BOLD))
    for path in REPORTS.values():
        print(c("  ├─ ", CYAN) + path)
    print(c("\nNEXT ACTION", MAGENTA + BOLD))
    print("  Open reports/output/mission-verdicts/mission-verdicts.md first, then validate HIGH/REVIEW rows manually under authorization.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Crazy colored VulnScope autonomous live CLI")
    parser.add_argument("--target", required=True)
    parser.add_argument("--include-subdomains", action="store_true")
    parser.add_argument("--include-google-pair", action="store_true")
    parser.add_argument("--max-workers", type=int, default=8)
    parser.add_argument("--max-cycles", type=int, default=8)
    parser.add_argument("--plan-only", action="store_true")
    args = parser.parse_args()
    if args.plan_only:
        return plan_only(args.target, args.include_subdomains, args.include_google_pair, args.max_cycles)
    return run_live(args.target, args.include_subdomains, args.include_google_pair, args.max_workers, args.max_cycles)


if __name__ == "__main__":
    raise SystemExit(main())
