#!/usr/bin/env python3
from __future__ import annotations

import json
import subprocess
import time
from pathlib import Path
from urllib.parse import urlparse

try:
    import yaml  # type: ignore
except Exception:
    yaml = None

OUT = Path("reports/output/kai-interface")
RUNTIME_CONFIG = Path("agent_config.runtime.yaml")
SESSION_SCOPE = Path("scope_policy.session.yaml")

BANNER = r'''
╔════════════════════════════════════════════════════════════════════╗
║                                                                    ║
║        KAI / VULNSCOPE — AUTONOMOUS COMMAND INTERFACE              ║
║        Safe Neural Review • Authorized Targets Only                 ║
║                                                                    ║
╚════════════════════════════════════════════════════════════════════╝
'''

MODEL_OPTIONS = {
    "a": {"name": "qwen2.5:14b", "label": "best reasoning, needs more RAM"},
    "b": {"name": "llama3.2", "label": "lighter, faster"},
    "c": {"name": "mistral", "label": "balanced"},
}

CHALLENGE_OPTIONS = {
    "a": {"name": "web", "label": "Web Application review"},
    "b": {"name": "boot2root", "label": "Boot2Root / lab host review"},
    "c": {"name": "portswigger", "label": "PortSwigger Web Academy lab"},
}


def normalize_target(raw: str) -> str:
    raw = raw.strip()
    if not raw:
        raise ValueError("Target cannot be empty")
    return raw if "://" in raw else "https://" + raw


def host_from_target(target: str) -> str:
    parsed = urlparse(normalize_target(target))
    return (parsed.hostname or parsed.netloc or target.replace("https://", "").replace("http://", "").split("/")[0]).lower()


def ask_choice(prompt: str, options: dict[str, dict[str, str]]) -> str:
    print(prompt)
    for key, value in options.items():
        print(f"  {key.upper()}. {value['name']} — {value['label']}")
    while True:
        answer = input("Choose option: ").strip().lower()
        if answer in options:
            return options[answer]["name"]
        print("Invalid option. Choose one of: " + ", ".join(k.upper() for k in options))


def ask_yes_no(prompt: str, default: bool = False) -> bool:
    suffix = "[Y/n]" if default else "[y/N]"
    raw = input(f"{prompt} {suffix}: ").strip().lower()
    if not raw:
        return default
    return raw in {"y", "yes"}


def write_runtime(target: str, model: str, challenge: str, include_subdomains: bool, two_accounts: bool) -> dict:
    OUT.mkdir(parents=True, exist_ok=True)
    host = host_from_target(target)
    hosts = [host]
    if include_subdomains:
        hosts.append("*." + host)
    SESSION_SCOPE.write_text("\n".join([
        "name: kai-vulnscope-session",
        "allowed_hosts:",
        *["  - '" + h + "'" for h in hosts],
        "blocked_hosts: []",
        "allowed_schemes:",
        "  - https",
        "  - http",
        "max_requests_per_minute: 30",
        "active_testing_allowed: false",
        "authenticated_testing_allowed: true",
        "notes: 'Generated by kai_safe_interface.py after explicit user consent. Safe review mode.'",
        "",
    ]), encoding="utf-8")
    config = {
        "target": target,
        "hosts": hosts,
        "scope_policy": str(SESSION_SCOPE),
        "model_provider": "ollama",
        "model_name": model,
        "cycles": 12,
        "verbosity": "normal",
        "dry_run": False,
        "include_subdomains": include_subdomains,
        "two_accounts": two_accounts,
        "monitoring_frequency": "none",
        "challenge_type": challenge,
    }
    if yaml:
        RUNTIME_CONFIG.write_text(yaml.safe_dump(config, sort_keys=False), encoding="utf-8")
    else:
        RUNTIME_CONFIG.write_text(json.dumps(config, indent=2), encoding="utf-8")
    audit = {"target": target, "host": host, "model": model, "challenge": challenge, "hosts": hosts, "two_accounts": two_accounts, "confirmed_at": time.time(), "config": str(RUNTIME_CONFIG), "scope": str(SESSION_SCOPE)}
    (OUT / "kai-session.json").write_text(json.dumps(audit, indent=2), encoding="utf-8")
    return audit


def run_agent() -> int:
    cmd = ["python3", "vulnscope_agent.py", "--config", str(RUNTIME_CONFIG), "--yes"]
    print("\n[+] Launching VulnScope neural agent")
    print("$ " + " ".join(cmd))
    return subprocess.call(cmd)


def main() -> int:
    print(BANNER)
    print("This interface follows the KAI-style setup flow while keeping VulnScope in safe authorized-review mode.")
    print("It will not run stealth, destructive actions, credential theft, or exploit chaining.\n")

    ollama = ask_yes_no("1. Do you have Ollama installed?", False)
    if not ollama:
        print("\nRun this first, then rerun this interface:")
        print("curl -fsSL https://ollama.ai/install.sh | sh")
        return 1

    model = ask_choice("\n2. Which free model do you want to use?", MODEL_OPTIONS)
    print(f"\nRun this before starting the agent if the model is not already pulled:")
    print(f"ollama pull {model}")
    pulled = ask_yes_no("Have you already pulled this model?", False)
    if not pulled:
        print("\nPull the model, then rerun this command:")
        print(f"ollama pull {model}")
        return 1

    target = normalize_target(input("\n3. What is your target? Enter authorized CTF/lab URL or IP: ").strip())
    challenge = ask_choice("\n4. What type of challenge is this?", CHALLENGE_OPTIONS)

    print("\nAUTHORIZATION CONFIRMATION")
    print("- Run only on CTF labs, training labs, PortSwigger Academy, or systems you own/have written permission to review.")
    print("- The tool will stay scope-locked and will run safe review modules only.")
    confirm = input(f"Type YES to confirm authorization for {target}: ").strip()
    if confirm != "YES":
        print("Consent not confirmed. Exiting.")
        return 1

    include_subdomains = ask_yes_no("Include subdomains in scope?", False)
    two_accounts = ask_yes_no("Use saved two-account comparison if available?", False)
    audit = write_runtime(target, model, challenge, include_subdomains, two_accounts)

    print("\n[+] Runtime config created: " + str(RUNTIME_CONFIG))
    print("[+] Scope policy created: " + str(SESSION_SCOPE))
    print("[+] Session audit: reports/output/kai-interface/kai-session.json")
    print(json.dumps(audit, indent=2))

    start = ask_yes_no("Start VulnScope neural agent now?", True)
    if start:
        return run_agent()
    print("\nStart later with:")
    print(f"python3 vulnscope_agent.py --config {RUNTIME_CONFIG} --yes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
