#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import shlex
import subprocess
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

from scope.policy import load_scope_policy

OUT = Path("reports/output/unified-mission")


class MissionStep:
    def __init__(self, label: str, command: str, timeout: int = 2400, critical: bool = False) -> None:
        self.label = label
        self.command = command
        self.timeout = timeout
        self.critical = critical

    def as_dict(self) -> dict[str, Any]:
        return {"label": self.label, "command": self.command, "timeout": self.timeout, "critical": self.critical}


def q(value: str) -> str:
    return shlex.quote(value)


def host_from_target(target: str) -> str:
    parsed = urlparse(target if "://" in target else "https://" + target)
    return parsed.netloc.split(":")[0].strip().lower()


def write_artemis_runtime_config(target: str) -> Path:
    OUT.mkdir(parents=True, exist_ok=True)
    host = host_from_target(target).replace("/", "_")
    path = OUT / f"artemis-{host}.yaml"
    path.write_text(
        "\n".join([
            "targets:",
            f"  - {target}",
            "passive_only: true",
            "require_scope_policy: true",
            "interval_minutes: 360",
            "report_every_cycles: 1",
            "google_search_limit: 5",
            "max_public_records: 500",
            "respect_rate_limits: true",
            "no_secret_values_in_reports: true",
            "notes: 'Generated by unified mission. Authorized passive mode.'",
            "",
        ]),
        encoding="utf-8",
    )
    return path


def build_stages(target: str, scope_policy: str, max_cycles: int, include_google_pair: bool) -> list[list[MissionStep]]:
    target_q = q(target)
    scope_q = q(scope_policy)
    host_q = q(host_from_target(target))
    artemis_cfg = q(str(write_artemis_runtime_config(target)))
    stages: list[list[MissionStep]] = []

    # Stage 1: repair/prepare. Tool installs are kept single-threaded to avoid PATH and package-manager races.
    stages.append([
        MissionStep("Neural Tool Mind", f"python3 tool_mind_cli.py --target {target_q} --mode crazy --install-needed --yes", 3600, critical=False),
    ])

    # Stage 2: independent low-risk intel and diagnostics in parallel.
    stages.append([
        MissionStep("Tool PATH Repair", "python3 tool_path_repair_cli.py", 600),
        MissionStep("Coverage Matrix", "python3 coverage_matrix.py", 600),
        MissionStep("Mega Tools Status", "python3 mega_tools_cli.py --status", 900),
        MissionStep("Passive Domain Recon", f"python3 domain_recon_cli.py --target {host_q}", 1800),
        MissionStep("AEGIS Public Search", f"python3 aegis_public_search_cli.py --target {target_q}", 900),
        MissionStep("AEGIS Feedback Planner", f"python3 aegis_feedback_cli.py --target {target_q}", 900),
        MissionStep("ARTEMIS Passive Intelligence", f"python3 artemis_autonomous_cli.py --config {artemis_cfg} --scope-policy {scope_q} --once", 2400),
    ])

    # Stage 3: evidence-generation and safe review modules in parallel.
    stage3 = [
        MissionStep("Autonomous Evidence Loop", f"python3 safe_loop_v2_cli.py --target {target_q} --mode comprehensive --scope-policy {scope_q} --max-cycles {max_cycles} --yes", 3600),
        MissionStep("Comprehensive Category Review", f"python3 comprehensive_suite_cli.py --target {target_q} --scope-policy {scope_q} --yes", 2400),
        MissionStep("Google/OAuth Context Review", "python3 google_context_cli.py", 900),
        MissionStep("Proxy Passive Bridge", f"python3 artemis_proxy_passive_cli.py --target {target_q} --limit 80", 900),
    ]
    if include_google_pair:
        stage3.append(MissionStep("Two Google Account Precision", f"python3 google_pair_cli.py --target {target_q} --profile default --max-pages 25 --skip-login --yes", 3600))
    stages.append(stage3)

    # Stage 4: correlation modules after evidence is present.
    stages.append([
        MissionStep("Advanced Modes Correlation", f"python3 vulnscope_modes_cli.py --target {target_q} --scope-policy {scope_q}", 2400),
        MissionStep("Normalize Evidence", f"python3 normalize_cli.py --target {target_q}", 900),
        MissionStep("Asset Graph", f"python3 asset_graph_cli.py --target {target_q}", 900),
        MissionStep("API Intelligence", f"python3 api_intel_cli.py --target {target_q}", 900),
        MissionStep("Auth Differential v2", "python3 auth_diff_v2_cli.py", 900),
        MissionStep("Target History", f"python3 target_history_cli.py --target {target_q}", 900),
    ])

    # Stage 5: reporting. Report depends on cards/ranking, so this is ordered.
    stages.append([
        MissionStep("Evidence Cards", f"python3 evidence_cards_cli.py --target {target_q}", 900),
    ])
    stages.append([
        MissionStep("Reportability Ranking", f"python3 reportability_cli.py --target {target_q}", 900),
    ])
    stages.append([
        MissionStep("Final Report", f"python3 report_v2_cli.py --target {target_q}", 900),
    ])
    stages.append([
        MissionStep("JARVIS Summary", f"python3 jarvis_summary_cli.py --target {target_q}", 900),
    ])
    return stages


def run_step(step: MissionStep) -> dict[str, Any]:
    started = time.time()
    try:
        proc = subprocess.run(["bash", "-lc", step.command], text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, timeout=step.timeout)
        return {
            **step.as_dict(),
            "ok": proc.returncode == 0,
            "exit_code": proc.returncode,
            "seconds": round(time.time() - started, 2),
            "output_tail": proc.stdout[-5000:],
        }
    except Exception as exc:
        return {**step.as_dict(), "ok": False, "error": str(exc), "seconds": round(time.time() - started, 2), "output_tail": ""}


def run_stage(stage_index: int, steps: list[MissionStep], max_workers: int) -> list[dict[str, Any]]:
    print(f"\n╔════════ STAGE {stage_index}: {len(steps)} parallel task(s) ════════╗")
    results: list[dict[str, Any]] = []
    workers = max(1, min(max_workers, len(steps)))
    with ThreadPoolExecutor(max_workers=workers) as executor:
        future_map = {executor.submit(run_step, step): step for step in steps}
        for future in as_completed(future_map):
            step = future_map[future]
            result = future.result()
            results.append(result)
            status = "OK" if result.get("ok") else "FAILED"
            print(f"[{status}] {step.label} — {result.get('seconds')}s")
            tail = str(result.get("output_tail") or "").strip()
            if tail:
                print(tail[-1200:])
    return results


def summarize(results: list[dict[str, Any]], target: str) -> None:
    ok = len([r for r in results if r.get("ok")])
    bad = len(results) - ok
    print("\n╔════════════════════════════════════════════════════════════════════╗")
    print("║              VULNSCOPE UNIFIED AUTONOMOUS MISSION                ║")
    print("╚════════════════════════════════════════════════════════════════════╝")
    print(f"Target : {target}")
    print(f"Tasks  : {len(results)} total | {ok} OK | {bad} failed/review")
    if bad:
        print("\nFailed/review tasks:")
        for r in results:
            if not r.get("ok"):
                print(f"- {r.get('label')} | exit={r.get('exit_code')} | see output tail in unified-mission.json")
    print("\nPrimary outputs:")
    print("- reports/output/unified-mission/unified-mission.md")
    print("- reports/output/evidence-cards/evidence-cards.md")
    print("- reports/output/reportability/reportability.md")
    print("- reports/output/report-v2/executive-report-v2.md")
    print("- reports/output/artemis/run/artemis-run.md")


def run_mission(target: str, scope_policy: str, max_cycles: int, max_workers: int, include_google_pair: bool, plan_only: bool = False) -> dict[str, Any]:
    OUT.mkdir(parents=True, exist_ok=True)
    decision = load_scope_policy(scope_policy).check(target)
    stages = build_stages(target, scope_policy, max_cycles, include_google_pair)
    plan = [[step.as_dict() for step in stage] for stage in stages]
    if plan_only:
        payload = {"target": target, "scope_policy": scope_policy, "plan_only": True, "stages": plan}
        (OUT / "unified-mission-plan.json").write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
        print(json.dumps({"plan": "reports/output/unified-mission/unified-mission-plan.json", "stages": len(stages)}, indent=2))
        return payload
    if not decision.allowed:
        payload = {"target": target, "allowed": False, "reason": decision.reason, "scope_policy": scope_policy, "stages": plan}
        (OUT / "unified-mission.json").write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
        print(json.dumps(payload, indent=2))
        return payload
    started = time.time()
    all_results: list[dict[str, Any]] = []
    for i, stage in enumerate(stages, 1):
        stage_results = run_stage(i, stage, max_workers=max_workers)
        all_results.extend(stage_results)
        if any((not r.get("ok")) and r.get("critical") for r in stage_results):
            break
    payload = {
        "target": target,
        "scope_policy": scope_policy,
        "allowed": True,
        "started_at": started,
        "ended_at": time.time(),
        "seconds": round(time.time() - started, 2),
        "max_workers": max_workers,
        "include_google_pair": include_google_pair,
        "summary": {"tasks": len(all_results), "ok": len([r for r in all_results if r.get("ok")]), "failed": len([r for r in all_results if not r.get("ok")])},
        "results": all_results,
        "stages": plan,
    }
    (OUT / "unified-mission.json").write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    lines = [f"# VulnScope Unified Autonomous Mission — {target}", "", f"Tasks: `{payload['summary']['tasks']}`", f"OK: `{payload['summary']['ok']}`", f"Failed/review: `{payload['summary']['failed']}`", "", "## Task Results"]
    for r in all_results:
        lines.append(f"- `{r.get('label')}` ok=`{r.get('ok')}` seconds=`{r.get('seconds')}` command=`{r.get('command')}`")
    (OUT / "unified-mission.md").write_text("\n".join(lines), encoding="utf-8")
    summarize(all_results, target)
    return payload


def main() -> int:
    parser = argparse.ArgumentParser(description="Unified parallel autonomous mission for VulnScope safe mode")
    parser.add_argument("--target", required=True)
    parser.add_argument("--scope-policy", default="scope_policy.session.yaml")
    parser.add_argument("--max-cycles", type=int, default=8)
    parser.add_argument("--max-workers", type=int, default=6)
    parser.add_argument("--include-google-pair", action="store_true")
    parser.add_argument("--plan-only", action="store_true")
    parser.add_argument("--yes", action="store_true")
    args = parser.parse_args()
    if not args.yes and not args.plan_only:
        answer = input("Run unified autonomous safe mission? type YES: ").strip()
        if answer != "YES":
            print(json.dumps({"started": False, "reason": "confirmation not provided"}, indent=2))
            return 1
    result = run_mission(args.target, args.scope_policy, args.max_cycles, args.max_workers, args.include_google_pair, args.plan_only)
    return 0 if result.get("allowed", True) is not False else 1


if __name__ == "__main__":
    raise SystemExit(main())
