#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import shlex
import subprocess
import time
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlparse

VERSION = "1.1.0-live-autonomous"
OUT = Path("reports/output/vulnscope-main")
SESSION_SCOPE = Path("scope_policy.session.yaml")
SESSION_AUDIT = Path("reports/output/authorization/vulnscope-session-confirmation.json")

BANNER = r"""
██╗   ██╗██╗   ██╗██╗     ███╗   ██╗███████╗ ██████╗ ██████╗ ██████╗ ███████╗
██║   ██║██║   ██║██║     ████╗  ██║██╔════╝██╔════╝██╔═══██╗██╔══██╗██╔════╝
██║   ██║██║   ██║██║     ██╔██╗ ██║███████╗██║     ██║   ██║██████╔╝█████╗  
╚██╗ ██╔╝██║   ██║██║     ██║╚██╗██║╚════██║██║     ██║   ██║██╔═══╝ ██╔══╝  
 ╚████╔╝ ╚██████╔╝███████╗██║ ╚████║███████║╚██████╗╚██████╔╝██║     ███████╗
  ╚═══╝   ╚═════╝ ╚══════╝╚═╝  ╚═══╝╚══════╝ ╚═════╝ ╚═════╝ ╚═╝     ╚══════╝
               LIVE AUTONOMOUS SECURITY INTELLIGENCE ENGINE
"""

RULES = [
    "Run only on a target you own or have explicit written authorization to test.",
    "Scope is locked to the target host and optional subdomains.",
    "The mission is evidence-first, rate-aware, non-destructive, and report-focused.",
    "Unauthorized testing is not allowed.",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="VulnScope live autonomous safe mission entrypoint")
    parser.add_argument("--version", action="store_true")
    parser.add_argument("--target", "--url", dest="target")
    parser.add_argument("--max-cycles", type=int, default=8)
    parser.add_argument("--max-workers", type=int, default=8)
    parser.add_argument("--include-subdomains", action="store_true")
    parser.add_argument("--include-google-pair", action="store_true")
    parser.add_argument("--skip-self-check", action="store_true")
    parser.add_argument("--yes", action="store_true")
    parser.add_argument("--plan-only", action="store_true")
    return parser.parse_args()


def normalize_target(raw: str) -> str:
    value = raw.strip()
    if not value:
        raise ValueError("Target URL cannot be empty")
    return value if "://" in value else "https://" + value


def host_from_target(target: str) -> str:
    parsed = urlparse(target if "://" in target else "https://" + target)
    host = (parsed.hostname or parsed.netloc or "").split(":")[0].strip().lower()
    if not host:
        raise ValueError("Invalid target. Use a URL/domain like https://example.com")
    return host


def ask_target() -> str:
    print("\n┌──────────────────────────── Target URL ────────────────────────────┐")
    print("│ Enter the website URL/domain you own or are authorized to test.     │")
    print("└─────────────────────────────────────────────────────────────────────┘")
    return normalize_target(input("Target URL: ").strip())


def ask_yes_no(prompt: str, default: bool = False) -> bool:
    suffix = "[Y/n]" if default else "[y/N]"
    raw = input(f"{prompt} {suffix}: ").strip().lower()
    if not raw:
        return default
    return raw in {"y", "yes"}


def write_session_scope(target: str, include_subdomains: bool) -> Path:
    host = host_from_target(target)
    allowed = [host]
    if include_subdomains and not host.replace(".", "").isdigit() and host != "localhost":
        allowed.append("*." + host)
    SESSION_SCOPE.write_text("\n".join([
        "name: vulnscope-live-session",
        "allowed_hosts:",
        *["  - '" + item + "'" for item in allowed],
        "blocked_hosts: []",
        "allowed_schemes:",
        "  - https",
        "  - http",
        "max_requests_per_minute: 30",
        "active_testing_allowed: false",
        "authenticated_testing_allowed: true",
        "notes: 'Generated by python3 vulnscope.py after explicit authorization confirmation. Live autonomous safe review.'",
        "",
    ]), encoding="utf-8")
    SESSION_AUDIT.parent.mkdir(parents=True, exist_ok=True)
    SESSION_AUDIT.write_text(json.dumps({
        "target": target,
        "host": host,
        "allowed_hosts": allowed,
        "include_subdomains": include_subdomains,
        "confirmed_authorization": True,
        "confirmed_at": datetime.now(timezone.utc).isoformat(),
        "scope_policy": str(SESSION_SCOPE),
        "rules": RULES,
    }, indent=2), encoding="utf-8")
    return SESSION_SCOPE


def command_to_str(command: list[str]) -> str:
    return " ".join(shlex.quote(x) for x in command)


def run_command(label: str, command: list[str], timeout: int = 7200) -> dict:
    print(f"\n╔════════ {label} ════════╗")
    print("$ " + command_to_str(command))
    started = time.time()
    try:
        proc = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1)
        lines: list[str] = []
        assert proc.stdout is not None
        for line in proc.stdout:
            clean = line.rstrip()
            lines.append(clean)
            if clean:
                print(clean[:240])
        code = proc.wait(timeout=timeout)
        return {"label": label, "command": command, "ok": code == 0, "exit_code": code, "seconds": round(time.time() - started, 2), "output_tail": "\n".join(lines[-100:])}
    except Exception as exc:
        print(f"[ERROR] {label}: {exc}")
        return {"label": label, "command": command, "ok": False, "error": str(exc), "seconds": round(time.time() - started, 2), "output_tail": ""}


def load_json(path: str | Path) -> dict:
    p = Path(path)
    if not p.exists():
        return {}
    try:
        data = json.loads(p.read_text(encoding="utf-8", errors="ignore"))
        return data if isinstance(data, dict) else {}
    except Exception:
        return {}


def summarize(target: str, history: list[dict]) -> dict:
    live = load_json("reports/output/autonomous-live/live-run.json")
    verdicts = load_json("reports/output/mission-verdicts/mission-verdicts.json")
    severity = verdicts.get("summary", {}).get("severity", {}) if isinstance(verdicts, dict) else {}
    rows = verdicts.get("rows", []) if isinstance(verdicts, dict) else []
    high_rows = [r for r in rows if str(r.get("severity", "")).upper() in {"CRITICAL", "HIGH"} or str(r.get("verdict", "")).upper() in {"REVIEW_HIGH", "VULNERABLE", "HIGH_PRIORITY"}]
    failed_steps = [h for h in history if not h.get("ok")]
    payload = {
        "target": target,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "live_summary": live,
        "severity_summary": severity,
        "high_priority_rows": high_rows[:25],
        "failed_or_review_steps": failed_steps[:25],
        "reports": {
            "live": "reports/output/autonomous-live/live-run.md",
            "preflight": "reports/output/mission-preflight/preflight.md",
            "mission_verdicts": "reports/output/mission-verdicts/mission-verdicts.md",
            "evidence_cards": "reports/output/evidence-cards/evidence-cards.md",
            "reportability": "reports/output/reportability/reportability.md",
            "final_report": "reports/output/report-v2/executive-report-v2.md",
            "authorization_audit": str(SESSION_AUDIT),
        },
    }
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "final-summary.json").write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    lines = [f"# VulnScope Final Mission Summary — {target}", "", "**FOR AUTHORIZED SECURITY TESTING ONLY – UNLAWFUL USE IS STRICTLY PROHIBITED.**", "", "## Severity Summary", "| Severity | Count |", "|---|---:|"]
    for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]:
        lines.append(f"| {sev} | {severity.get(sev, 0)} |")
    lines += ["", "## High Priority Rows"]
    if high_rows:
        for r in high_rows[:25]:
            lines.append(f"- `{r.get('module')}` `{r.get('item')}` verdict=`{r.get('verdict')}` severity=`{r.get('severity')}` evidence=`{str(r.get('evidence', ''))[:300]}`")
    else:
        lines.append("- No high-priority row generated. Review manual candidates in mission-verdicts.md.")
    lines += ["", "## Reports"]
    for name, path in payload["reports"].items():
        lines.append(f"- {name}: `{path}`")
    (OUT / "final-summary.md").write_text("\n".join(lines), encoding="utf-8")
    return payload


def print_final(payload: dict) -> None:
    print("\n╔════════════════════════════════════════════════════════════════════╗")
    print("║                    VULNSCOPE FINAL OUTPUT                        ║")
    print("╚════════════════════════════════════════════════════════════════════╝")
    print(f"Target           : {payload.get('target')}")
    print("Severity Summary : " + json.dumps(payload.get("severity_summary", {}), ensure_ascii=False))
    high = payload.get("high_priority_rows", [])
    if high:
        print("\nHigh-priority rows:")
        for r in high[:10]:
            print(f"- [{r.get('severity')}] {r.get('module')} | {r.get('verdict')} | {r.get('item')}")
    else:
        print("\nNo high-priority row generated. Check mission-verdicts.md for candidates and NOT_TESTED rows.")
    print("\nOpen these files:")
    for path in payload.get("reports", {}).values():
        print(f"- {path}")


def main() -> int:
    args = parse_args()
    if args.version:
        print(f"VulnScope {VERSION}")
        return 0
    print(BANNER)
    target = normalize_target(args.target) if args.target else ask_target()
    host = host_from_target(target)
    include_subdomains = args.include_subdomains
    include_google_pair = args.include_google_pair
    if not args.yes:
        print("\nAuthorization confirmation required:")
        for item in RULES:
            print(f"- {item}")
        print(f"\nTarget host: {host}")
        include_subdomains = ask_yes_no("Include subdomains in scope?", default=False)
        include_google_pair = ask_yes_no("Run two-account Google precision if saved sessions exist?", default=False)
        confirm = input("\nType YES if you own/have full authorization to test this target: ").strip()
        if confirm != "YES":
            print("\n[!] Authorization not confirmed. Mission cancelled.")
            return 1
    scope = write_session_scope(target, include_subdomains)
    print(f"\n[+] Session scope created: {scope}")
    print(f"[+] Authorization audit: {SESSION_AUDIT}")
    history: list[dict] = []
    if not args.skip_self_check and not args.plan_only:
        history.append(run_command("System Self-Check", ["python3", "repo_health_cli.py", "--install-python-deps", "--tool-update"], timeout=3600))
    live_cmd = ["python3", "autonomous_live_cli.py", "--target", target, "--max-cycles", str(args.max_cycles), "--max-workers", str(args.max_workers)]
    if include_subdomains:
        live_cmd.append("--include-subdomains")
    if include_google_pair:
        live_cmd.append("--include-google-pair")
    if args.plan_only:
        live_cmd.append("--plan-only")
    history.append(run_command("Live Autonomous Engine", live_cmd, timeout=7200))
    if not args.plan_only:
        history.append(run_command("Mission Verdict Consolidation", ["python3", "mission_verdicts_cli.py", "--target", target], timeout=900))
        history.append(run_command("Final Report Builder", ["python3", "report_v2_cli.py", "--target", target], timeout=900))
        history.append(run_command("JARVIS Terminal Summary", ["python3", "jarvis_summary_cli.py", "--target", target], timeout=900))
    payload = summarize(target, history)
    print_final(payload)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
